#!/bin/bash

files=""
args=""

for arg in $@
do
  if [ "${arg:0:1}" = "-" ]; then
    args="$args -plugin-arg-boa ${arg:1}"
  else
    files="$files $arg"
  fi
done

if [ "$files" != "" ]; then
  ../llvm/Debug+Asserts/bin/clang -g -O0 -c -emit-llvm ${files} -o /dev/stdout | ../llvm/Debug+Asserts/bin/opt -load build/boa.so -boa > /dev/null
else
  echo -e " usage : \033[1m./boa [flags] <source files>\033[0m"
  echo ""
  echo "possible flags - "
  echo -e "  \033[1m-log\033[0m    - print log to stdout"
  echo -e "  \033[1m-blame\033[0m  - print minimal set of constraints that cause each overrun"
fi
