#!/bin/bash

BOADIR=`dirname $0`

files=""
args=""
BOA_SO="$BOADIR/build/boa.so"
CLANG="$BOADIR/../llvm/Debug+Asserts/bin/clang"
OPT="$BOADIR/../llvm/Debug+Asserts/bin/opt"

FLAGS=""

for arg in $@
do
  # Bash switch statement:
  case "$arg" in
    -log)
      args="$args -logfile /dev/stderr"
    ;;
    -output_glpk|-blame|-no_pointer_analysis|-ignore_literals)
      FLAGS="$FLAGS $arg"
    ;;
    *)
      files="$files $arg"
    ;;
  esac
done

if [ "$files" != "" ]; then
  $CLANG -g -O0 -c -emit-llvm ${files} -o /dev/stdout | $OPT -load $BOA_SO $args -boa $FLAGS > /dev/null
else
  echo -e " usage : \033[1m./boa [flags] <source files>\033[0m"
  echo ""
  echo "possible flags - "
  echo -e "  \033[1m-log\033[0m                 - print log to stdout"
  echo -e "  \033[1m-blame\033[0m               - print a set of constraints that cause each overrun"
  echo -e "  \033[1m-glpk\033[0m                - pring glpk to log"
  echo -e "  \033[1m-no_pointer_analysis\033[0m - do not generate pointer analysis constraints"  
  echo -e "  \033[1m-ignore_literals\033[0m     - don't report buffer overruns on string literals"  
fi
